Flexible:
Workcenter:         TC-110
  RGB:                76;67;174
  Release:            0
  Status:             A
Machine:            TC-110.01
    Release:            0
    Status:             A

Workcenter:         Feeder
  RGB:                119;181;11
  Release:            0
  Status:             A
Machine:            Feeder.01
    Release:            0
    Status:             A

Workcenter:         TC-77
  RGB:                163;109;71
  Release:            0
  Status:             A
Machine:            TC-77.01
    Release:            0
    Status:             A
Machine:            TC-77.02
    Release:            0
    Status:             A
Machine:            TC-77.03
    Release:            0
    Status:             A
Machine:            TC-77.04
    Release:            0
    Status:             A

Workcenter:         C400
  RGB:                190;17;140
  Release:            0
  Status:             A
Machine:            C400.01
    Release:            0
    Status:             A
Machine:            C400.02
    Release:            0
    Status:             A
Machine:            C400.03
    Release:            0
    Status:             A

Workcenter:         TC-110_2
  Comment:            Stage 2
  RGB:                4;81;242
  Release:            0
  Status:             B
Machine:            TC-110_2.01
    Release:            0
    Status:             B

Workcenter:         Feeder_2
  Comment:            Stage 2
  RGB:                72;24;1
  Release:            0
  Status:             B
Machine:            Feeder_2.01
    Release:            0
    Status:             B

Workcenter:         TC-77_2
  Comment:            Stage 2
  RGB:                85;172;125
  Release:            0
  Status:             B
Machine:            TC-77_2.01
    Release:            0
    Status:             B
Machine:            TC-77_2.02
    Release:            0
    Status:             B
Machine:            TC-77_2.03
    Release:            0
    Status:             B
Machine:            TC-77_2.04
    Release:            0
    Status:             B

Workcenter:         C400_2
  Comment:            Stage 2
  RGB:                135;65;25
  Release:            0
  Status:             B
Machine:            C400_2.01
    Release:            0
    Status:             B
Machine:            C400_2.02
    Release:            0
    Status:             B
Machine:            C400_2.03
    Release:            0
    Status:             B

